---
title: "Workshop 2"
format: html
editor: visual
---



```{r}
library(tidyverse)
library(readr)
```


```{r}
table1
table2
table3
```

```{r}
# using tidy with table1
table1 %>% 
  mutate(rate = cases / population * 10000)

table1 %>%  
  count(year, wt = cases)

ggplot(table1, aes(year, cases)) +
  geom_line(aes(group = country), color = "grey50") + 
  geom_point(aes(color = country))
```

```{r}
# pivoting our data so it will be longer/easier to work with - increase the number of rows and decrease the number of columns
billboard # viewing the dataset 

```

```{r}
billboard %>% 
  pivot_longer( 
    cols = starts_with("wk"), # specifies the column we want to pivot 
    names_to = "week", # the names the variable stored in the columns name (something that we rename, will be printed out in the final output)
    values_to = "rank") # also a name we made, 
```

```{r}
# removing all the NAs in the dataset 
billboard %>% 
  pivot_longer( 
    cols = starts_with("wk"), 
    names_to = "week", 
    values_to = "rank", 
    values_drop_na = TRUE) 
```

```{r}
# pivot longer example 
df <- tribble( 
  ~id, ~bp1, ~bp2, 
  "A", 100, 120, 
  "B", 140, 115, 
  "C", 120, 125)
```


```{r}
df %>% 
  pivot_longer(
    cols = bp1:bp2, 
    names_to = "measurement", 
    values_to = "value"
  )
```

```{r}
# pivot wider example
cms_patient_experience %>% 
  distinct(measure_cd, measure_title)
```

```{r}
# pivot wider example, not quite right 
cms_patient_experience %>%  
  pivot_wider(
    names_from = measure_cd, 
    values_from = prf_rate
  )
```

```{r}
cms_patient_experience %>% 
  pivot_wider(
    id_cols = starts_with("org"), 
    names_from = measure_cd, 
    values_from = prf_rate 
  )
```

```{r}
# another pivot wider examples 
df <- tribble(
  ~id, ~measurement, ~value,
  "A",        "bp1",    100,
  "B",        "bp1",    140,
  "B",        "bp2",    115, 
  "A",        "bp2",    120,
  "A",        "bp3",    105
)
```

```{r}
df %>% 
  pivot_wider(
    names_from = measurement,
    values_from = value
  )
```

```{r}
df %>% 
  distinct(measurement) %>% 
  pull()
```

```{r}
df %>% 
  select(-measurement, -value) %>%
  distinct() %>% 
  mutate(x = NA, y = NA, z = NA) # generates an empty dataframe 
  
```
## Pivoting with Palmer Penguins
```{r}
library(palmerpenguins)
```

```{r}
penguins_long <- penguins |>
  pivot_longer(
    cols = c(bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g),
    names_to = "measurement_type",
    values_to = "value"
  )
# View the result
head(penguins_long)

```

```{r}
penguins_long %>% 
  drop_na(value) %>% 
  ggplot(aes(x = value, fill = species)) +
  geom_histogram(bins = 30, alpha = 0.7, colour = "black") +
  facet_wrap(~ measurement_type, scales = "free_x") +
  theme_minimal() +
  labs(
    title = "Morphometric distributions across penguin species",
    x = "Measurement value",
    y = "Frequency"

  )
```

```{r}
# widening data with pivot_wider 
mass_summary <- penguins %>% 
  drop_na(body_mass_g) %>%  
  group_by(species, island) %>%  
  summarise(mean_mass = mean(body_mass_g))

head(mass_summary)
```

```{r}
mass_matrix <- mass_summary %>%  
  pivot_wider(
    names_from = island, 
    values_from = mean_mass
  )

head(mass_matrix)
```

## Table 3 Example
```{r}
table3 %>%  
  separate(rate, into = c("cases", "population"))
# will split values wherever it sees a non-alphanumeric character (something that isnt a number or letter). 
```

```{r}
# if we want to use a specific character to separate a column
table3 %>%  
  separate(rate, into = c("cases", "population"), sep = "/")
```

```{r}
# passing a vector of integers will interpret the integers as positions to split at
table3 %>%  
  separate(year, into = c("century", "year"), sep = 2)
```

## Using the unite() function, inverse of separate() 
```{r}
table5 %>% 
  unite(new, century, year, sep = "")
# have to have the sep = empty or else it will separate with an underscore 
```

```{r}
library(tidyverse)

# A remarkably messy data frame of field sites - put into a new dataset first? 
messy_sites <- tibble(
  site_id = c(" Nelly Bay", "nelly_bay", "NELLY BAY", " Geoffrey_Bay ", "geoffrey bay")
)

# Using stringr within mutate to standardize the text
clean_sites <- messy_sites |>
  mutate(
    # 1. Convert everything to lowercase
    site_clean = str_to_lower(site_id),
    # 2. Replace any spaces with underscores
    site_clean = str_replace_all(site_clean, pattern = " ", replacement = "_"),
    # 3. Trim any leading or trailing whitespace (invisible spaces at the ends)
    site_clean = str_trim(site_clean)
  )

print(clean_sites)

# after creating a new tibble, we can combine/replace the old dataset's variables with this one 

```
## Date and Time functions
```{r}
library(lubridate)
# practicing with different date formats 
date_1 <- dmy("25/12/2026")
date_2 <- ymd("2026-12-25")

date_1 == date_2
# R now recognizes these as the same date 

```


```{r}
# practicing with specific timestamps, including hour, mins, secs
sensor_data <- tibble(
  raw_time = c("14-05-2026 08:30:00", "14-05-2026 08:45:00", "14-05-2026 09:00:00"),
  temperature = c(24.5, 24.6, 24.4)
)

# Converting character strings to true POSIXct datetime objects
sensor_clean <- sensor_data |>
  mutate(
    true_time = dmy_hms(raw_time)
  )

print(sensor_clean)

```


## Joining tables together 
```{r}
# Table 1: biological observation data 
observations <- tibble(
  site_code = c("NB", "GB", "MI", "NB", "HB"),
  species = c("Trout", "Snapper", "Trout", "Cod", "Trout"),
  count = c(5, 2, 1, 3, 8)
)

# Table 2: spatial metadata
site_metadata <- tibble(
  site_code = c("NB", "GB", "MI", "RP", "WP"),
  zone = c("Marine National Park", "Conservation Park", "Habitat Protection", "General Use", "Other Use"),
  lat = c(-19.16, -19.15, -19.14, -19.12, -19.11)
)

# both of these tables created, and now we join 
```

```{r}
# left_join = keeps all rows from the left table and adds matching rows from the right table. If there is no match, it fills with NA.

joined_data <- observations %>%  
  left_join(site_metadata, by = "site_code")

print(joined_data)
```

```{r}
# inner_join = keeps only rows that have matching values in both tables.

matched_data <- observations %>%  
  inner_join(site_metadata, by = join_by("site_code"))

glimpse(matched_data)
```

```{r}
# anti_join = keeps only rows from the left table that do not have a match in the right table.
missing_context <- observations %>% 
  anti_join(site_metadata, by = join_by("site_code"))

```

## Handling Missing Values 
```{r}
# conversiting with na_if 
logger_data <- tibble(
  depth_m = c(10, 20, 30, 40),
  temp_c = c(24.5, 24.1, -999, 23.5)) # -999 is a known sensor error code

# Convert the -999 error codes to true NA values
fixed_logger <- logger_data |>
  mutate(temp_c = na_if(temp_c, -999))

print(fixed_logger)

```

```{r}
# replacing missing values with coalesce()
shark_counts <- tibble(
  site = c("Reef_A", "Reef_B", "Reef_C"),
  shark_count = c(3, NA, 5)) # The NA here actually means 0 sharks were seen

# Replace NA with 0 
shark_fixed <- shark_counts |>
  mutate(shark_count = coalesce(shark_count, 0))

print(shark_fixed)


```


```{r}
# fixing the NaN - not a number - could occur when you divide a number by 0
cpue_data <- tibble(
  site = c("Bay_1", "Bay_2"),
  catch = c(10, 0),
  effort_hours = c(2, 0))

# Calculating CPUE (catch / effort)
cpue_calc <- cpue_data %>% 
  mutate(
    cpue = catch / effort_hours)

print(cpue_calc)


```


```{r}
# raw catch of coral trout species 
raw_catch <- tibble(
  site = c("Reef_1", "Reef_1", "Reef_2"),
  species = c("Pmaculatus", "Pleopardus", "Pmaculatus"),
  count = c(5, 2, 8))

```


```{r}
# Force inclusion of hidden zero-catch data
full_catch_matrix <- raw_catch |>
  complete(site, species, fill = list(count = 0))

print(full_catch_matrix)

```

```{r}
# manually removing the row that contains an NA
sensor_log <- tibble(
  day = 1:4,
  salinity = c(35.2, 35.1, NA, 35.3)
)

# Remove any row where salinity is missing
clean_log <- sensor_log |>
  drop_na(salinity)

```

```{r}
# Make sure packages are loaded
library(tidyverse)
library(palmerpenguins)

# The messy metadata provided by your colleague
island_metadata <- tibble(
  island_name = c(" biscoe", "Dream ", "Torgersen"),
  station_install = c("15/01/2003", "22-03-2004", "05/11/2001"),
  latitude = c(-64.81, -64.73, -64.76)
)

print(island_metadata)

```

```{r}


clean_metadata <- island_metadata |>
  mutate(
    island_name = str_trim(island_name), # Remove leading/trailing whitespace
    island_name = str_to_title(island_name), # Convert to title case
    station_install = dmy(station_install) # Convert to Date object
  )



penguins_spatial <- penguins |>
  left_join(clean_metadata, by = join_by(island == island_name)) # left_join to combine datasets 

head(penguins_spatial)
```


```{r}
# a clean publication ready table showing the maximum body mass recorded for each species, separated by island 
penguins_clean <- penguins_spatial %>% 
  drop_na(body_mass_g) %>% # drops anything with an NA in the body_mass_g column 
  group_by(species, island) %>% # groups by species and island 
  summarise(max_mass = max(body_mass_g), .groups = "drop") %>% 
  pivot_wider(
    names_from = island,
    values_from = max_mass
  )

head(penguins_clean)
```

## 2.12 Keystone Exercise 

```{r}

```










